'use client'

import {
    FiMonitor, FiCode, FiShoppingCart, FiSettings, FiLayers,
    FiSearch, FiZap, FiShield, FiUsers, FiTrendingUp, FiGlobe,
    FiFileText, FiCheckCircle, FiClock, FiCreditCard, FiPackage,
    FiBarChart2, FiTruck, FiRefreshCw, FiTarget, FiSmartphone,
    FiLayout, FiEye, FiMousePointer, FiStar, FiUploadCloud, FiMail,
} from 'react-icons/fi'
import {
    FaReact, FaNodeJs, FaWordpress, FaPhp, FaDocker,
    FaApple, FaAndroid, FaFigma, FaShippingFast,
    FaGoogle, FaFacebookF, FaInstagram, FaYoutube,
} from 'react-icons/fa'
import {
    SiNextdotjs, SiLaravel, SiMysql, SiTailwindcss, SiTypescript, SiRedis,
    SiFlutter, SiDart, SiKotlin, SiSwift, SiFirebase, SiGraphql,
    SiWoocommerce, SiShopify, SiMagento, SiStripe,
    SiAdobexd, SiAdobeillustrator, SiAdobephotoshop,
    SiMiro, SiInvision, SiRazorpay, SiPaypal,
    SiGoogleanalytics, SiGooglesearchconsole, SiSemrush,
    SiReact,
} from 'react-icons/si'

const SERVICE_CONFIGS = {
    'website-development': {
        badge: 'Web Development',
        heroTitle: 'Custom Website Development Services',
        heroSubtitle: 'From corporate websites to complex web applications — we build fast, secure, and SEO-optimised websites using React, Next.js, and Laravel that drive real business results.',
        heroIcon: FiMonitor,
        heroColor: '#0A2463',
        serviceName: 'Website Development',
        overviewTitle: 'End-to-End Website Development',
        overviewDesc: 'At Prominent TechnoLabs, we design and develop websites that are not just visually stunning — they are built to perform. Every project is approached with an SEO-first mindset, mobile-first design, and clean scalable code. Whether you need a company brochure site, a custom web portal, or a complex web application, our full-stack team delivers on time and within budget.',
        overviewHighlights: [
            'React, Next.js & Laravel — modern tech stack',
            'Google Core Web Vitals optimised for speed',
            'Mobile-first responsive design on all devices',
            'SEO-ready structure with clean semantic HTML',
            'Secure authentication, APIs & database design',
            'Dedicated project manager & transparent updates',
        ],
        overviewStats: [
            { value: '50+', label: 'Websites Built' },
            { value: '99%', label: 'Satisfaction' },
            { value: '48h', label: 'Avg. Response' },
        ],
        offers: [
            { Icon: FiGlobe, color: '#0A2463', title: 'Corporate & Business Websites', desc: 'Professional multi-page business websites that build credibility, attract leads, and convert visitors into customers.' },
            { Icon: FiCode, color: '#0891b2', title: 'Custom Web Applications', desc: 'Scalable portals, SaaS dashboards, booking systems, and business tools built on React + Laravel REST APIs.' },
            { Icon: FiShoppingCart, color: '#FF6600', title: 'E-Commerce Websites', desc: 'WooCommerce and custom Laravel e-commerce stores with product management, cart, payment gateway & order tracking.' },
            { Icon: FiLayers, color: '#7c3aed', title: 'Landing Page Design', desc: 'High-converting campaign landing pages with A/B testing ready structure and fast page load for better Quality Score.' },
            { Icon: FiSettings, color: '#059669', title: 'WordPress Development', desc: 'Custom WordPress themes, plugin development, WooCommerce integrations, and full site migrations & maintenance.' },
            { Icon: FiMonitor, color: '#d97706', title: 'Website Maintenance', desc: 'Ongoing support, security patches, performance tuning, content updates, and uptime monitoring for your live site.' },
        ],
        process: [
            { num: '01', Icon: FiFileText, title: 'Discovery & Planning', desc: 'We start by understanding your business goals, target audience, competitors, and technical requirements.' },
            { num: '02', Icon: FiLayers, title: 'UI/UX Design', desc: 'Our designers create wireframes and high-fidelity Figma mockups for your approval before a single line of code is written.' },
            { num: '03', Icon: FiCode, title: 'Development', desc: 'Full-stack development with clean code, REST APIs, database design, admin panels, and third-party integrations.' },
            { num: '04', Icon: FiShield, title: 'Testing & QA', desc: 'Cross-browser testing, mobile responsiveness checks, performance audits, and security vulnerability scans.' },
            { num: '05', Icon: FiZap, title: 'Launch & Support', desc: 'Smooth deployment to your hosting, DNS setup, SSL, Google Analytics & Search Console configuration, and post-launch monitoring.' },
        ],
        technologies: [
            { Icon: FaReact, color: '#61DBFB', name: 'React' },
            { Icon: SiNextdotjs, color: '#000000', name: 'Next.js' },
            { Icon: SiLaravel, color: '#FF2D20', name: 'Laravel' },
            { Icon: FaNodeJs, color: '#68A063', name: 'Node.js' },
            { Icon: FaWordpress, color: '#21759b', name: 'WordPress' },
            { Icon: FaPhp, color: '#4F5D95', name: 'PHP' },
            { Icon: SiMysql, color: '#00758F', name: 'MySQL' },
            { Icon: SiRedis, color: '#DC382D', name: 'Redis' },
            { Icon: SiTypescript, color: '#3178C6', name: 'TypeScript' },
            { Icon: SiTailwindcss, color: '#06B6D4', name: 'Tailwind CSS' },
            { Icon: FaDocker, color: '#2496ED', name: 'Docker' },
            { Icon: FiGlobe, color: '#0A2463', name: 'REST API' },
        ],
        whyUs: [
            { Icon: FiSearch, title: 'SEO-First Development', desc: "Every website we build follows Google's Core Web Vitals standards — fast loading, mobile-friendly, and semantically structured for top rankings." },
            { Icon: FiZap, title: 'On-Time Delivery', desc: 'We follow agile sprints with weekly milestone updates. 90% of our projects are delivered on or before the agreed deadline.' },
            { Icon: FiUsers, title: 'Dedicated Team', desc: 'You get a dedicated project manager, UI designer, frontend developer, backend developer, and QA tester — not freelancers.' },
        ],
        faqs: [
            { q: 'How long does it take to build a website?', a: 'A standard 5-10 page corporate website takes 3-4 weeks. Complex web applications with custom portals and APIs typically take 8-16 weeks depending on scope.' },
            { q: 'What technologies do you use for website development?', a: 'We primarily use React and Next.js for the frontend, Laravel for the backend API, and MySQL for the database. For WordPress projects we use custom themes and plugins.' },
            { q: 'Do you provide website hosting and domain setup?', a: 'Yes, we help you choose the right hosting (Hostinger, AWS, DigitalOcean), set up your domain DNS, configure SSL certificates, and deploy your website.' },
            { q: 'How much does a website cost?', a: 'Website costs range from $199 for a landing page to $2,000+ for large enterprise web applications. Contact us for a detailed quote tailored to your requirements.' },
            { q: 'Will my website be mobile-friendly?', a: 'Absolutely. Every website we build is fully responsive and tested across iPhone, Android, iPad, and all major browsers (Chrome, Safari, Firefox, Edge).' },
        ],
    },

    'mobile-app-development': {
        badge: 'Mobile Apps',
        heroTitle: 'Mobile App Development Services',
        heroSubtitle: 'Build beautiful, high-performance iOS and Android apps using Flutter and React Native. Our mobile team delivers apps that users love — from MVP to enterprise-grade products.',
        heroIcon: FiSmartphone,
        heroColor: '#FF6600',
        serviceName: 'Mobile App Development',
        overviewTitle: 'iOS & Android App Development',
        overviewDesc: 'We build mobile applications that combine beautiful design with rock-solid performance. Whether you need a cross-platform app with Flutter, a native iOS app in SwiftUI, or a React Native hybrid app — our mobile team has you covered. We handle the full lifecycle from concept and wireframing to App Store submission and post-launch maintenance.',
        overviewHighlights: [
            'Flutter for pixel-perfect cross-platform apps (iOS + Android)',
            'React Native for JavaScript-based cross-platform development',
            'Native Swift/Kotlin for premium performance iOS & Android apps',
            'Firebase for authentication, real-time DB & push notifications',
            'REST & GraphQL API integration with your backend',
            'App Store & Google Play Store submission assistance',
        ],
        overviewStats: [
            { value: '20+', label: 'Apps Launched' },
            { value: '2', label: 'Platforms' },
            { value: '99%', label: 'App Approved' },
        ],
        offers: [
            { Icon: SiFlutter, color: '#54C5F8', title: 'Flutter App Development', desc: 'Single codebase, two platforms. Flutter delivers native-like performance with stunning UI — ideal for startups wanting fast delivery.' },
            { Icon: SiReact, color: '#61DBFB', title: 'React Native Development', desc: 'JavaScript-powered cross-platform apps with access to a massive ecosystem of packages, perfect for teams with web backgrounds.' },
            { Icon: FaApple, color: '#555555', title: 'iOS App Development', desc: 'Native Swift/SwiftUI iOS apps built for performance and App Store compliance, including iPad and Apple Watch extensions.' },
            { Icon: FaAndroid, color: '#3DDC84', title: 'Android App Development', desc: 'Native Kotlin Android apps optimised for the diverse Android device landscape, supporting the latest Android 15 features.' },
            { Icon: FiLayout, color: '#7c3aed', title: 'App UI/UX Design', desc: 'HIG and Material Design 3 compliant UI designs in Figma, optimised for touch interaction and usability.' },
            { Icon: FiSettings, color: '#059669', title: 'App Maintenance & Updates', desc: 'Ongoing support including OS compatibility updates, bug fixes, new feature additions, and App Store rating management.' },
        ],
        process: [
            { num: '01', Icon: FiFileText, title: 'Requirement Analysis', desc: "We map out your app's user stories, features, platform requirements, and monetisation strategy." },
            { num: '02', Icon: FaFigma, title: 'Wireframe & Prototype', desc: 'Interactive Figma prototypes for every screen so you see the app before development begins.' },
            { num: '03', Icon: FiCode, title: 'Development', desc: 'Iterative sprint-based development with bi-weekly demos. You see progress every step of the way.' },
            { num: '04', Icon: FiShield, title: 'QA & Device Testing', desc: 'Testing on real iOS and Android devices across multiple screen sizes, OS versions, and network conditions.' },
            { num: '05', Icon: FiUploadCloud, title: 'App Store Submission', desc: 'We handle the full App Store and Google Play submission, metadata, screenshots, and review process.' },
        ],
        technologies: [
            { Icon: SiFlutter, color: '#54C5F8', name: 'Flutter' },
            { Icon: SiDart, color: '#0175C2', name: 'Dart' },
            { Icon: SiReact, color: '#61DBFB', name: 'React Native' },
            { Icon: SiTypescript, color: '#3178C6', name: 'TypeScript' },
            { Icon: FaApple, color: '#555555', name: 'Swift' },
            { Icon: SiKotlin, color: '#7F52FF', name: 'Kotlin' },
            { Icon: SiSwift, color: '#FA7343', name: 'SwiftUI' },
            { Icon: SiFirebase, color: '#FFCA28', name: 'Firebase' },
            { Icon: SiGraphql, color: '#E10098', name: 'GraphQL' },
            { Icon: FaAndroid, color: '#3DDC84', name: 'Android' },
        ],
        whyUs: [
            { Icon: FiStar, title: 'App Store Expertise', desc: 'We have successfully submitted 20+ apps to the App Store and Google Play with 100% approval rate. We know what reviewers look for.' },
            { Icon: FiZap, title: 'Fast MVP Development', desc: 'Using Flutter, we can build a production-ready MVP in 6-8 weeks — allowing you to validate your idea quickly before investing in scale.' },
            { Icon: FiUsers, title: 'End-to-End Service', desc: "From UI design to API development to app submission — one team handles everything, so there's no coordination overhead for you." },
        ],
        faqs: [
            { q: 'Do you develop for both iOS and Android?', a: 'Yes. We build cross-platform apps using Flutter or React Native that run on both iOS and Android from a single codebase, or native apps in Swift (iOS) and Kotlin (Android) for maximum performance.' },
            { q: 'How long does mobile app development take?', a: 'A simple app with 5-8 screens takes 6-8 weeks. A complex app with features like real-time chat, maps, payments, or social feeds typically takes 12-20 weeks.' },
            { q: 'Should I choose Flutter or React Native?', a: 'Flutter is our top recommendation for most projects — it offers native-like performance, consistent UI across platforms, and faster development. React Native is a great choice if your team is already experienced in JavaScript/React.' },
            { q: 'Do you help with App Store submission?', a: 'Yes, we handle the entire submission process including Apple Developer account setup, screenshots, descriptions, privacy policy, and responding to review rejections.' },
            { q: 'What is the cost of mobile app development in India?', a: 'A basic app starts from $649. Mid-complexity apps with backend APIs range from $1,299 to $4,500. Enterprise apps are priced on scope. Contact us for a detailed estimate.' },
        ],
    },

    'ui-ux-design': {
        badge: 'Design Services',
        heroTitle: 'UI/UX Design Services',
        heroSubtitle: 'We create stunning, intuitive interfaces that captivate users and convert visitors into customers. From wireframes to pixel-perfect Figma prototypes — every pixel is purposeful.',
        heroIcon: FiLayout,
        heroColor: '#7c3aed',
        serviceName: 'UI/UX Design',
        overviewTitle: 'Design That Drives Results',
        overviewDesc: 'Good design is not just about looking great — it is about making users feel at ease, reducing friction, and guiding them toward their goals. Our UI/UX design team blends aesthetics with psychology to craft interfaces that are both beautiful and genuinely usable. We follow a research-driven design process covering everything from user personas and journey maps to interactive Figma prototypes ready for developer handoff.',
        overviewHighlights: [
            'User research, personas & journey mapping',
            'Low-fidelity wireframes to validate structure',
            'High-fidelity Figma & Adobe XD prototypes',
            'Design system & component library creation',
            'Interaction design & micro-animation specs',
            'Developer-ready handoff with Figma Dev Mode',
        ],
        overviewStats: [
            { value: '50+', label: 'Screens Designed' },
            { value: '100%', label: 'Client Approved' },
            { value: '5x', label: 'Faster Handoff' },
        ],
        offers: [
            { Icon: FiMonitor, color: '#0A2463', title: 'Website UI Design', desc: 'Beautiful, conversion-focused website designs with consistent visual language, typography, and brand alignment.' },
            { Icon: FiSmartphone, color: '#FF6600', title: 'Mobile App UI Design', desc: 'iOS and Android app interfaces built to Human Interface Guidelines and Material Design 3 standards.' },
            { Icon: FiEye, color: '#7c3aed', title: 'UX Research & Audit', desc: 'Heuristic evaluation, user interviews, usability testing, and heat map analysis to identify friction points.' },
            { Icon: FiFileText, color: '#0891b2', title: 'Wireframing & Prototyping', desc: 'Clickable Figma prototypes that simulate real user flows — approved before any development begins.' },
            { Icon: FiStar, color: '#d97706', title: 'Brand Identity Design', desc: 'Logo design, color palette, typography selection, and brand guidelines for consistent cross-channel identity.' },
            { Icon: FiLayout, color: '#059669', title: 'Design System Creation', desc: 'Scalable design systems with reusable components, spacing tokens, icons, and developer documentation.' },
        ],
        process: [
            { num: '01', Icon: FiUsers, title: 'Discovery & Research', desc: 'We study your users, business goals, competitors, and existing product to define design direction and priorities.' },
            { num: '02', Icon: FiFileText, title: 'Wireframing', desc: 'Low-fidelity wireframes to map out information architecture and screen flows — fast to iterate and easy to validate.' },
            { num: '03', Icon: FiLayout, title: 'Visual Design', desc: 'High-fidelity mockups applying your brand colors, typography, spacing, and UI components in Figma.' },
            { num: '04', Icon: FiMousePointer, title: 'Interactive Prototype', desc: 'Clickable Figma prototype with transitions and animations — test real user flows before development starts.' },
            { num: '05', Icon: FiCheckCircle, title: 'Handoff & Support', desc: 'Developer-ready design handoff via Figma Dev Mode or Zeplin, with design QA support throughout development.' },
        ],
        technologies: [
            { Icon: FaFigma, color: '#F24E1E', name: 'Figma' },
            { Icon: SiAdobexd, color: '#FF61F6', name: 'Adobe XD' },
            { Icon: SiAdobeillustrator, color: '#FF9A00', name: 'Illustrator' },
            { Icon: SiAdobephotoshop, color: '#31A8FF', name: 'Photoshop' },
            { Icon: SiMiro, color: '#FFD02F', name: 'Miro' },
            { Icon: SiInvision, color: '#FF3366', name: 'InVision' },
            { Icon: FiLayout, color: '#7c3aed', name: 'Design System' },
        ],
        whyUs: [
            { Icon: FiEye, title: 'User-Centred Approach', desc: 'Every design decision is backed by user research and best-practice UX principles — not personal preference or trends.' },
            { Icon: FiZap, title: 'Fast Iteration Cycles', desc: 'We deliver wireframes within 48 hours and high-fidelity designs within a week. Feedback rounds are structured and efficient.' },
            { Icon: FiCheckCircle, title: 'Dev-Ready Deliverables', desc: 'Designs are handed off with complete specs, assets, and component documentation so there are zero guesses for developers.' },
        ],
        faqs: [
            { q: 'What design tools do you use?', a: 'We primarily use Figma for all UI/UX work — it allows real-time collaboration with clients, interactive prototyping, and seamless developer handoff via Dev Mode. We also use Adobe XD, Illustrator, and Photoshop when needed.' },
            { q: 'How many design revisions are included?', a: 'Our standard engagement includes 3 rounds of revisions at each stage (wireframe, visual design, prototype). Additional revision rounds can be added as needed.' },
            { q: 'Do you provide source files after completion?', a: 'Yes, you receive all Figma source files, exported assets (SVGs, PNGs), icon libraries, and brand guidelines upon project completion and final payment.' },
            { q: 'Can you redesign my existing website or app?', a: 'Absolutely. We start with a UX audit of your current product, identify usability issues and conversion bottlenecks, then design an improved version that retains familiarity while fixing problems.' },
            { q: 'Do you work with developers or just do design?', a: "We do both. If you have your own development team, we deliver design handoff assets. If not, our in-house developers can build exactly what we design — no translation cost." },
        ],
    },

    'cms-ecommerce': {
        badge: 'E-Commerce',
        heroTitle: 'CMS & E-Commerce Development',
        heroSubtitle: 'Build a powerful, scalable online store that converts visitors into customers. We develop on WooCommerce, Shopify, Magento, and custom Laravel — with full payment, inventory, and order management.',
        heroIcon: FiShoppingCart,
        heroColor: '#0891b2',
        serviceName: 'CMS & E-Commerce',
        overviewTitle: 'Scalable E-Commerce Solutions',
        overviewDesc: "Your e-commerce platform is your most important sales channel — and it needs to be fast, reliable, and easy to manage. We build online stores optimised for conversion, with intuitive product browsing, a frictionless checkout experience, automated order processing, and seamless integration with payment gateways and logistics providers. Whether you sell 10 products or 10,000 SKUs, we build a platform that grows with you.",
        overviewHighlights: [
            'WooCommerce, Shopify & Magento expert development',
            'Custom Laravel e-commerce for unique requirements',
            'Mobile-first responsive storefront design',
            'Payment gateway integration (Razorpay, Stripe, PayPal, UPI)',
            'Inventory, order & return management systems',
            'GST invoice automation & tax configuration',
        ],
        overviewStats: [
            { value: '15+', label: 'Stores Built' },
            { value: '3x', label: 'Avg. Sales Growth' },
            { value: '99.9%', label: 'Uptime' },
        ],
        offers: [
            { Icon: SiWoocommerce, color: '#96588A', title: 'WooCommerce Development', desc: 'Custom WooCommerce stores with bespoke themes, plugin development, payment integration, and performance optimisation.' },
            { Icon: SiShopify, color: '#96BF48', title: 'Shopify Store Development', desc: 'Shopify and Shopify Plus store setup, custom app development, theme customisation, and migration from other platforms.' },
            { Icon: SiMagento, color: '#EE672F', title: 'Magento Development', desc: 'Enterprise-grade Magento 2 stores for large catalogues, B2B operations, and multi-store configurations.' },
            { Icon: FiCode, color: '#0A2463', title: 'Custom CMS Development', desc: 'Bespoke content management systems built on Laravel — fully tailored to your workflow with role-based access.' },
            { Icon: FiPackage, color: '#d97706', title: 'Multi-Vendor Marketplace', desc: 'Build your own Amazon-like multi-seller marketplace with vendor dashboards, commission management, and seller onboarding.' },
            { Icon: FiBarChart2, color: '#059669', title: 'Analytics & Reporting', desc: 'Built-in sales dashboards, inventory reports, customer behaviour analytics, and Google Analytics 4 e-commerce tracking.' },
        ],
        process: [
            { num: '01', Icon: FiFileText, title: 'Consultation', desc: 'We understand your products, audience, fulfilment process, and required integrations before recommending a platform.' },
            { num: '02', Icon: FiShoppingCart, title: 'Platform Selection', desc: 'We recommend the right platform (WooCommerce, Shopify, Magento, or custom) based on your budget, catalogue size, and growth plans.' },
            { num: '03', Icon: FiSettings, title: 'Design & Setup', desc: 'Custom storefront design, product catalogue setup, payment gateway configuration, and shipping zone setup.' },
            { num: '04', Icon: FiShield, title: 'Testing & Security', desc: 'Full checkout flow testing, payment sandbox testing, mobile responsiveness, page speed audit, and security hardening.' },
            { num: '05', Icon: FiZap, title: 'Launch & Training', desc: 'Go-live with SSL, CDN configuration, staff training on managing products, orders, and promotions using the admin panel.' },
        ],
        technologies: [
            { Icon: SiWoocommerce, color: '#96588A', name: 'WooCommerce' },
            { Icon: SiShopify, color: '#96BF48', name: 'Shopify' },
            { Icon: SiMagento, color: '#EE672F', name: 'Magento' },
            { Icon: FaWordpress, color: '#21759b', name: 'WordPress' },
            { Icon: SiLaravel, color: '#FF2D20', name: 'Laravel' },
            { Icon: SiMysql, color: '#00758F', name: 'MySQL' },
            { Icon: SiStripe, color: '#635BFF', name: 'Stripe' },
            { Icon: FiTruck, color: '#FF6600', name: 'Shiprocket' },
        ],
        whyUs: [
            { Icon: FiZap, title: 'Mobile-Optimised Storefronts', desc: 'Over 70% of e-commerce traffic is mobile. Every store we build is designed and tested for flawless mobile shopping experience.' },
            { Icon: FiShield, title: 'Secure Checkout', desc: 'PCI-DSS compliant payment setup, SSL encryption, fraud prevention rules, and CAPTCHA protection on all checkout forms.' },
            { Icon: FiUsers, title: 'Easy Self-Management', desc: 'We build stores that non-technical team members can manage — add products, update prices, process orders, and run promotions without developer help.' },
        ],
        faqs: [
            { q: 'Should I use WooCommerce or Shopify?', a: 'Shopify is great for getting started quickly with less technical overhead. WooCommerce on WordPress gives you full control, lower long-term costs, and more flexibility. We will recommend the best fit for your specific situation.' },
            { q: 'Can you migrate my existing store to a new platform?', a: 'Yes, we handle full data migrations including products, categories, customer accounts, order history, and SEO redirects. We have migrated from Magento to WooCommerce, OpenCart to Shopify, and custom systems to Laravel.' },
            { q: 'Which payment gateways do you integrate?', a: 'For Indian stores: Razorpay, PayU, CCAvenue, UPI, and COD. For international: Stripe, PayPal, and Square. We also support subscription billing via Razorpay Subscriptions and Stripe Billing.' },
            { q: 'Can customers manage their own store after delivery?', a: 'Absolutely. We provide full training videos or live training sessions for your team. WooCommerce and Shopify have very user-friendly admin panels that non-technical staff can manage day-to-day.' },
            { q: 'How much does an e-commerce website cost in India?', a: 'A WooCommerce store with up to 100 products starts from $499. A Shopify store with custom design starts from $349. Custom Laravel marketplace platforms start from $1,999.' },
        ],
    },

    'payment-shipping-api': {
        badge: 'API Integration',
        heroTitle: 'Payment & Shipping API Integration',
        heroSubtitle: 'Streamline your checkout and fulfilment pipeline with battle-tested payment gateway and shipping API integrations. We connect Stripe, Razorpay, PayPal, Shiprocket, and more — securely and reliably.',
        heroIcon: FiCreditCard,
        heroColor: '#059669',
        serviceName: 'Payment & Shipping API',
        overviewTitle: 'Seamless Payment & Shipping Integration',
        overviewDesc: "Payment and shipping are the final — and most critical — steps in any customer's journey. A slow or broken checkout costs you real revenue. We specialise in integrating India's top payment gateways and logistics APIs with your web or mobile application, following PCI-DSS security guidelines and testing every edge case — including failed payments, refunds, and courier exceptions — before going live.",
        overviewHighlights: [
            'Razorpay, Stripe, PayPal & PayU payment gateway integration',
            'UPI, Net Banking, Credit/Debit Card & Wallet support',
            'Subscription & recurring payment billing setup',
            'COD, EMI & Buy Now Pay Later integration',
            'Shiprocket, Delhivery & BlueDart shipping API',
            'Automated GST invoice & e-way bill generation',
        ],
        overviewStats: [
            { value: '10+', label: 'Gateways Integrated' },
            { value: '100%', label: 'Secure & PCI-DSS' },
            { value: '48h', label: 'Integration Time' },
        ],
        offers: [
            { Icon: SiRazorpay, color: '#072654', title: 'Razorpay Integration', desc: 'Full Razorpay integration including Payment Links, Subscriptions, Route (marketplace payouts), and Razorpay Magic Checkout.' },
            { Icon: SiStripe, color: '#635BFF', title: 'Stripe Integration', desc: 'Stripe Checkout, Stripe Billing (subscriptions), Stripe Connect (marketplace), multi-currency support, and webhook handling.' },
            { Icon: SiPaypal, color: '#003087', title: 'PayPal Integration', desc: 'PayPal Standard, PayPal Express Checkout, and Braintree SDK integration for international transactions.' },
            { Icon: FiGlobe, color: '#0891b2', title: 'UPI & Net Banking', desc: 'UPI AutoPay (mandates), QR code payment, Net Banking, and wallet integrations (Paytm, PhonePe, Amazon Pay).' },
            { Icon: FiTruck, color: '#FF6600', title: 'Shiprocket & Delhivery', desc: 'End-to-end shipping API integration — auto rate calculation, order booking, AWB generation, tracking & webhook updates.' },
            { Icon: FiRefreshCw, color: '#d97706', title: 'Refund & Dispute Automation', desc: 'Automated refund workflows, chargeback handling, dispute evidence submission, and reconciliation reporting.' },
        ],
        process: [
            { num: '01', Icon: FiFileText, title: 'Requirement Analysis', desc: 'We map your payment flows — one-time, recurring, marketplace splits — and choose the right gateway and integration method.' },
            { num: '02', Icon: FiCode, title: 'Sandbox Setup', desc: 'API keys, webhook endpoints, and test environment setup so every flow is thoroughly tested before touching live money.' },
            { num: '03', Icon: FiSettings, title: 'Integration Build', desc: 'Backend API endpoints, frontend payment UI (hosted checkout or custom), webhook listeners, and database schema updates.' },
            { num: '04', Icon: FiCheckCircle, title: 'End-to-End Testing', desc: 'Test every scenario: successful payment, failed card, refund, partial refund, subscription renewal, webhook delivery, and timeout handling.' },
            { num: '05', Icon: FiShield, title: 'Go-Live & Monitoring', desc: 'Production key activation, PCI-DSS checklist review, payment dashboard setup, and alert configuration for failed transactions.' },
        ],
        technologies: [
            { Icon: SiRazorpay, color: '#072654', name: 'Razorpay' },
            { Icon: SiStripe, color: '#635BFF', name: 'Stripe' },
            { Icon: SiPaypal, color: '#003087', name: 'PayPal' },
            { Icon: FiCreditCard, color: '#0891b2', name: 'CCAvenue' },
            { Icon: FiTruck, color: '#059669', name: 'Delhivery' },
            { Icon: FiGlobe, color: '#d97706', name: 'PayU' },
            { Icon: FiShield, color: '#555555', name: 'PCI-DSS' },
            { Icon: FiZap, color: '#FF6600', name: 'Webhooks' },
        ],
        whyUs: [
            { Icon: FiShield, title: 'Security-First Integration', desc: 'We follow PCI-DSS guidelines, use server-side token handling, never log card data, and configure Content Security Policy headers for payment pages.' },
            { Icon: FiZap, title: 'End-to-End Ownership', desc: 'We handle the complete integration — from gateway account setup to webhook handling — so you do not need to coordinate between multiple vendors.' },
            { Icon: FiCode, title: 'Multi-Currency & Multi-Gateway', desc: 'Support for INR, USD, GBP, EUR and more. We also build failover logic so if one gateway is down, your checkout automatically switches to a backup.' },
        ],
        faqs: [
            { q: 'Which payment gateway is best for Indian businesses?', a: 'Razorpay is our top recommendation for businesses primarily targeting Indian customers — it supports all Indian payment methods (UPI, Net Banking, wallets) and has the best developer experience. Stripe is recommended for international or SaaS businesses with global customers.' },
            { q: 'How long does payment gateway integration take?', a: 'A single payment gateway integration (e.g., Razorpay on an existing website) typically takes 2-5 days including testing. Full e-commerce payment setup with subscriptions and refund workflows takes 1-2 weeks.' },
            { q: 'Do payment gateways charge annual fees?', a: 'Most Indian payment gateways (Razorpay, PayU) charge a per-transaction fee (typically 2-2.5% + GST) with no annual fee. International gateways like Stripe charge 2.9% + $0.30 per transaction.' },
            { q: 'Do you integrate shipping with payment — auto order creation?', a: 'Yes. We build automated workflows where a successful payment triggers order creation in your system, sends a confirmation email to the customer, and books the shipment via Shiprocket or Delhivery API automatically.' },
            { q: 'Is our customer card data secure?', a: 'Absolutely. We never store raw card data on your servers. Payment tokenisation is handled entirely by the gateway (Razorpay/Stripe), and all communication is over TLS 1.3. Your servers never touch sensitive card information.' },
        ],
    },

    'digital-marketing': {
        badge: 'Digital Marketing',
        heroTitle: 'Digital Marketing Services',
        heroSubtitle: 'Reach your ideal audience, generate qualified leads, and grow your revenue with data-driven SEO, Google Ads, social media marketing, and content strategies that deliver measurable results.',
        heroIcon: FiTrendingUp,
        heroColor: '#d97706',
        serviceName: 'Digital Marketing',
        overviewTitle: 'Marketing That Delivers Measurable ROI',
        overviewDesc: 'Digital marketing is not about vanity metrics — it is about business results. Our team creates and executes marketing strategies that bring qualified traffic to your website, convert that traffic into leads, and then into paying customers. We work across SEO, paid advertising, social media, and content — backed by analytics and regular reporting so you always know exactly where your money is going.',
        overviewHighlights: [
            'Search Engine Optimisation (SEO) — Google Page 1 rankings',
            'Google Ads (Search, Display, Shopping, YouTube)',
            'Facebook & Instagram Ads with advanced audience targeting',
            'Social media management (Instagram, LinkedIn, YouTube)',
            'Content writing, blog strategy & link building',
            'Monthly analytics reports with ROI breakdown',
        ],
        overviewStats: [
            { value: '3x', label: 'Avg. Traffic Growth' },
            { value: '10+', label: 'Brands Managed' },
            { value: 'Top 5', label: 'Google Rankings' },
        ],
        offers: [
            { Icon: FiSearch, color: '#0A2463', title: 'Search Engine Optimisation', desc: 'Technical SEO, on-page optimisation, keyword research, backlink building, and Core Web Vitals improvements to rank your website on Google Page 1.' },
            { Icon: FaGoogle, color: '#EA4335', title: 'Google Ads (PPC)', desc: 'Search Ads, Display Ads, Shopping Ads, and YouTube video ads managed with exact match targeting, negative keywords, and CRO-focused landing pages.' },
            { Icon: FaFacebookF, color: '#1877F2', title: 'Facebook & Instagram Ads', desc: 'Lead generation, retargeting, catalog sales, and brand awareness campaigns with creative A/B testing and pixel-based audience building.' },
            { Icon: FiBarChart2, color: '#7c3aed', title: 'Social Media Marketing', desc: 'Content creation, scheduling, community management, and growth strategy for Instagram, LinkedIn, Facebook, and YouTube channels.' },
            { Icon: FiFileText, color: '#059669', title: 'Content Writing & Strategy', desc: 'SEO-optimised blog articles, website copy, product descriptions, email campaigns, and ad copies crafted for conversion.' },
            { Icon: FiTarget, color: '#d97706', title: 'Analytics & ROI Reporting', desc: 'GA4 setup, Search Console monitoring, conversion tracking, and monthly reports showing leads, cost-per-acquisition, and revenue attribution.' },
        ],
        process: [
            { num: '01', Icon: FiBarChart2, title: 'Audit & Research', desc: 'Website SEO audit, competitor analysis, keyword gap analysis, and advertising account review to identify quick wins and long-term opportunities.' },
            { num: '02', Icon: FiTarget, title: 'Strategy Creation', desc: '90-day marketing roadmap with channel allocation, budget breakdown, content calendar, and KPIs agreed upon before execution begins.' },
            { num: '03', Icon: FiFileText, title: 'Content & Creative', desc: 'Ad creatives, landing pages, blog articles, social media content, and email sequences designed to match your brand voice and convert.' },
            { num: '04', Icon: FiZap, title: 'Campaign Launch', desc: 'SEO implementation, ad campaign setup, tracking pixel installation, Google Analytics goals, and Search Console property verification.' },
            { num: '05', Icon: FiCheckCircle, title: 'Monitor & Optimise', desc: 'Weekly performance reviews, bid adjustments, A/B testing, content updates, and monthly comprehensive ROI reports delivered to you.' },
        ],
        technologies: [
            { Icon: FaGoogle, color: '#EA4335', name: 'Google Ads' },
            { Icon: SiGoogleanalytics, color: '#E37400', name: 'GA4' },
            { Icon: SiGooglesearchconsole, color: '#4285F4', name: 'Search Console' },
            { Icon: FaFacebookF, color: '#1877F2', name: 'Meta Ads' },
            { Icon: FaInstagram, color: '#E1306C', name: 'Instagram' },
            { Icon: FaYoutube, color: '#FF0000', name: 'YouTube' },
            { Icon: SiSemrush, color: '#FF642D', name: 'Semrush' },
        ],
        whyUs: [
            { Icon: FiStar, title: 'Data-Driven Decisions', desc: 'Every strategy is backed by keyword data, competitor benchmarks, and audience insights — not guesswork. We track everything and optimise based on what the numbers show.' },
            { Icon: FiBarChart2, title: 'Transparent Reporting', desc: 'Monthly reports show exactly where your budget went, how many leads were generated, cost per lead, and which channels are delivering the best ROI.' },
            { Icon: FiUsers, title: 'Dedicated Specialist', desc: 'You get a dedicated digital marketing manager who understands your business, tracks performance weekly, and proactively suggests improvements.' },
        ],
        faqs: [
            { q: 'How long does SEO take to show results?', a: 'SEO is a long-term investment. You can typically expect to see traffic improvements within 3-4 months, significant ranking jumps by month 6, and compounding growth from month 9 onward. Competitive niches may take 12 months for top 3 positions.' },
            { q: 'What is the minimum budget for Google Ads in India?', a: 'We recommend a minimum ad spend of $199-$299/month for Google Search Ads to gather meaningful data. Our management fee is separate from ad spend.' },
            { q: 'Do you provide content for social media posts?', a: 'Yes. Our social media management service includes graphic design, caption writing, hashtag research, and scheduling. We create a monthly content calendar and get your approval before posting.' },
            { q: 'Can you run ads for my app on the App Store and Play Store?', a: 'Yes. We run Apple Search Ads (for App Store) and Google UAC campaigns (for Play Store) to drive app installs with accurate cost-per-install tracking.' },
            { q: 'How do you measure the success of digital marketing?', a: 'We track KPIs based on your goals — for e-commerce: revenue, ROAS, and cost-per-purchase. For lead generation: CPL, qualified leads, and conversion rate. For brand awareness: reach, impressions, and engagement rate.' },
        ],
    },
}

export default SERVICE_CONFIGS
